# Generated by Django 6.0.6 on 2026-06-24 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=80)),
                ('zip_code', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit / Debit Card'), ('upi', 'UPI')], default='cod', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('audio', 'Audio'), ('wearables', 'Wearables'), ('computing', 'Computing'), ('power', 'Power')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Shown crossed out next to the price if set.', max_digits=8, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('stock_status', models.CharField(choices=[('in', 'In stock'), ('low', 'Low stock'), ('out', 'Out of stock')], default='in', max_length=10)),
                ('image', models.CharField(help_text='Path under static/, e.g. images/headphones.svg', max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the store without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
